In [1]:
import numpy as np

In [3]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [5]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.linspace(1,5,15)

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [29]:
a=4/14
np.arange(1,5+a,a)

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [60]:
a=14
b=37
c=7
np.linspace(a,b,c)

array([14.        , 17.83333333, 21.66666667, 25.5       , 29.33333333,
       33.16666667, 37.        ])

In [61]:
d=(b-a)/(c-1)
np.arange(a,b+d,d)

array([14.        , 17.83333333, 21.66666667, 25.5       , 29.33333333,
       33.16666667, 37.        ])

In [62]:
d

3.8333333333333335